before_install:
  - cp toolchains.xml.example ~/.m2/toolchains.xml
jobs:
  include:
    - language: java
      jdk: openjdk8
      install:
        - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -DjdkLevel=8
      script:
        - mvn test -B -DjdkLevel=8
    - language: java
      jdk: openjdk11
      script:
        - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -DjdkLevel=11
      script:
        - mvn test -B -DjdkLevel=11
    - language: java
      jdk: openjdk14
      script:
        - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -DjdkLevel=14
      script:
        - mvn test -B -DjdkLevel=14
notifications:
  email:
    - ansell.peter@gmail.com
