jobs:
  include:
    - language: java
      jdk: openjdk8
      before_install:
        - mkdir -p "~/.m2/"
        - cp "toolchains.xml.template" "~/.m2/toolchains.xml"
        - ls -lah "~/.m2"
        - sed -i "s/JDK_VENDOR/openjdk/g" "~/.m2/toolchains.xml"
        - sed -i "s/JDK_VERSION/8/g" "~/.m2/toolchains.xml"
      install:
        - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -DjdkLevel=8
      script:
        - mvn test -B -DjdkLevel=8
    - language: java
      jdk: openjdk11
      before_install:
        - mkdir -p "~/.m2/"
        - cp toolchains.xml.template ~/.m2/toolchains.xml
        - ls -lah "~/.m2"
        - sed -i "s/JDK_VENDOR/openjdk/g" "~/.m2/toolchains.xml"
        - sed -i "s/JDK_VERSION/11/g" "~/.m2/toolchains.xml"
      install:
        - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -DjdkLevel=11
      script:
        - mvn test -B -DjdkLevel=11
    - language: java
      jdk: openjdk14
      before_install:
        - mkdir -p "~/.m2/"
        - cp toolchains.xml.template ~/.m2/toolchains.xml
        - ls -lah "~/.m2"
        - sed -i "s/JDK_VENDOR/openjdk/g" "~/.m2/toolchains.xml"
        - sed -i "s/JDK_VERSION/14/g" "~/.m2/toolchains.xml"
      install:
        - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -DjdkLevel=14
      script:
        - mvn test -B -DjdkLevel=14
notifications:
  email:
    - ansell.peter@gmail.com
