jobs:
  include:
    - language: java
      jdk: openjdk8
      before_install:
        - mkdir -p "${HOME}/.m2/"
        - cp "toolchains.xml.template" "${HOME}/.m2/toolchains.xml"
        - ls -lah "${HOME}/.m2"
        - sed -i "s|JAVA_HOME|${JAVA_HOME}|g" "${HOME}/.m2/toolchains.xml"
        - sed -i "s/JDK_VENDOR/openjdk/g" "${HOME}/.m2/toolchains.xml"
        - sed -i "s/JDK_VERSION/8/g" "${HOME}/.m2/toolchains.xml"
        - cat "${HOME}/.m2/toolchains.xml"
      install:
        - ls -lah "${JAVA_HOME}"
        - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -DjdkLevel=8
      script:
        - mvn test -B -DjdkLevel=8
    - language: java
      jdk: openjdk11
      before_install:
        - mkdir -p "${HOME}/.m2/"
        - cp "toolchains.xml.template" "${HOME}/.m2/toolchains.xml"
        - ls -lah "${HOME}/.m2"
        - sed -i "s|JAVA_HOME|${JAVA_HOME}|g" "${HOME}/.m2/toolchains.xml"
        - sed -i "s/JDK_VENDOR/openjdk/g" "${HOME}/.m2/toolchains.xml"
        - sed -i "s/JDK_VERSION/8/g" "${HOME}/.m2/toolchains.xml"
        - cat "${HOME}/.m2/toolchains.xml"
      install:
        - ls -lah "${JAVA_HOME}"
        - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -DjdkLevel=11
      script:
        - mvn test -B -DjdkLevel=11
    - language: java
      jdk: openjdk14
      before_install:
        - mkdir -p "${HOME}/.m2/"
        - cp "toolchains.xml.template" "${HOME}/.m2/toolchains.xml"
        - ls -lah "${HOME}/.m2"
        - sed -i "s|JAVA_HOME|${JAVA_HOME}|g" "${HOME}/.m2/toolchains.xml"
        - sed -i "s/JDK_VENDOR/openjdk/g" "${HOME}/.m2/toolchains.xml"
        - sed -i "s/JDK_VERSION/8/g" "${HOME}/.m2/toolchains.xml"
        - cat "${HOME}/.m2/toolchains.xml"
      install:
        - ls -lah "${JAVA_HOME}"
        - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -DjdkLevel=14
      script:
        - mvn test -B -DjdkLevel=14
notifications:
  email:
    - ansell.peter@gmail.com
